# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/arrow-down-from-line, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x7e\x7e\x18\x18\x7e\x7e\x3c\x18'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
