# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/arrow-right, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x00\x18\x0c\x7e\x7e\x0c\x18\x00'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
