# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/attach, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x1e\x3f\x7e\xff\xff\xfe\xfc\x78'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
