# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/book-open-check, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\xff\xff\x99\x9f\x9f\xff\xff\x18'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
