# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/book-marked, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x7e\x56\x5e\x5e\x42\x7e\x42\x7e'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
