# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/box, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x3c\x7e\xe7\xff\xdb\xdb\x7e\x3c'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
