#!/usr/bin/env python3
"""
icons/build_icons.py

Converts PNG icons in icons/src/ into MicroPython 1-bit bitmap modules in icons/.

Each PNG is read pixel-by-pixel. Any pixel with alpha > 0 becomes a "1" bit.
The 1-bit data is packed MSB-first, row-major, into a bytes literal — the same
shape as fonts/ modules produced by font_to_py, so drawing/icon.py can iterate
over it without any extra format awareness.

Usage:
    python3 icons/build_icons.py
    python3 icons/build_icons.py --src icons/src --out icons

Source PNGs should be:
    - Native pixel resolution (no upscaling — designed at the target size)
    - Transparent background, opaque silhouette
    - Any size — width and height are captured per-icon

Re-run whenever you add or update icons. The generated *.py files are auto-generated.
"""

import argparse
import re
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    raise SystemExit("Pillow not installed. Run: pip3 install Pillow")


SCRIPT_DIR = Path(__file__).parent
DEFAULT_SRC = SCRIPT_DIR / "src"
DEFAULT_OUT = SCRIPT_DIR


def to_module_name(stem):
    """heart-filled → heart_filled, Check Mark → check_mark.

    Strips common Figma export suffixes like ', Size=8px'.
    """
    # Drop everything from the first comma onward (Figma's variant suffix)
    stem = stem.split(",", 1)[0]
    name = re.sub(r"[^A-Za-z0-9]+", "_", stem).strip("_").lower()
    if name and name[0].isdigit():
        name = "_" + name
    return name


def pack_1bit(img):
    """Pack image alpha into MSB-first 1-bit bytes, row-major.

    A pixel is "on" if its alpha channel is > 0. For grayscale or RGB PNGs without
    alpha, falls back to "any non-white" pixel = on.
    """
    w, h = img.size
    px = img.load()
    bands = img.getbands()
    has_alpha = "A" in bands

    out = bytearray((w * h + 7) // 8)
    bit = 0
    for y in range(h):
        for x in range(w):
            p = px[x, y]
            if has_alpha:
                on = p[-1] > 0
            else:
                # Treat any non-white as "on" (for PNGs with no alpha layer)
                if isinstance(p, int):
                    on = p < 128
                else:
                    on = sum(p[:3]) < 255 * 3
            if on:
                out[bit // 8] |= 1 << (7 - (bit % 8))
            bit += 1
    return bytes(out)


def format_bytes_literal(data, width=12):
    """Pretty-print a bytes literal with line wrapping."""
    parts = []
    for i in range(0, len(data), width):
        chunk = data[i:i + width]
        parts.append("b'" + "".join("\\x%02x" % b for b in chunk) + "'")
    return " \\\n    ".join(parts)


_TEMPLATE = """# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/{src_name}
# Size: {w}x{h}

_W = {w}
_H = {h}
_DATA = {data}


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
"""


def convert(src_path, out_dir):
    img = Image.open(src_path).convert("RGBA")
    w, h = img.size
    packed = pack_1bit(img)
    module_name = to_module_name(src_path.stem)
    out_path = out_dir / (module_name + ".py")
    out_path.write_text(
        _TEMPLATE.format(
            src_name=src_path.name,
            w=w, h=h,
            data=format_bytes_literal(packed),
        ),
        encoding="utf-8",
    )
    return module_name, w, h, len(packed)


def main():
    parser = argparse.ArgumentParser(description="Build pico-ui-kit icon modules from PNG sources.")
    parser.add_argument("--src", default=str(DEFAULT_SRC), help="Source directory of PNGs (default: icons/src)")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Output directory for .py modules (default: icons/)")
    args = parser.parse_args()

    src_dir = Path(args.src)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    pngs = sorted(src_dir.glob("*.png"))
    if not pngs:
        print(f"No PNGs found in {src_dir}/. Drop some in and re-run.")
        return

    print(f"Building {len(pngs)} icon module(s) from {src_dir}/ → {out_dir}/")
    for p in pngs:
        name, w, h, n_bytes = convert(p, out_dir)
        print(f"  icons/{name}.py — {w}x{h} ({n_bytes} bytes)")
    print("Done.")


if __name__ == "__main__":
    main()
