# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/chart-line, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\xc0\xc0\xc2\xfe\xfc\xc0\xff\x7f'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
