# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/chevron-left, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x00\x0c\x1c\x38\x38\x1c\x0c\x00'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
