# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/chevron-last, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x00\x24\x34\x1c\x1c\x34\x24\x00'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
