# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/circle-dashed, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x1c\x66\xc2\x81\x81\x43\x66\x38'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
