# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/copy, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\xfc\x84\xbf\xa1\xa1\xe1\x21\x3f'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
