# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/expand, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\xe7\xe7\xff\x3c\x3c\xff\xe7\xe7'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
