# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/file, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x7c\x4e\x4e\x42\x42\x42\x42\x7e'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
