# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/folder-plus, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\xf0\xff\x9f\x99\xbd\x99\xff\x00'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
