# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/grid-2x2, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x7e\xff\xdb\xff\xff\xdb\xff\x7e'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
