# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/landmark, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x3c\xff\xff\x7e\x7e\x7e\x7e\xff'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
