# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/languages, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x20\xf8\x70\x74\x76\x0e\x0f\x1b'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
