# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/layout-grid, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\xff\xff\xdb\xff\xff\xdb\xff\xff'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
