# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/leaf, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x06\x3f\x7b\x4b\x7b\xf6\xfc\x80'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
