# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/link, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x0e\x1b\x3b\x7f\xfe\x98\xf8\x70'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
