# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/list-checks, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x00\x3f\xef\x4f\x3f\xff\x6f\x00'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
