# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/loader-circle, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x38\x7c\xc0\xc3\xc3\xc3\x7e\x3c'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
