# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/log-in, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x0e\x0f\x1b\xff\xff\x1b\x0f\x0e'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
