# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/log-out, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x70\xf0\xc6\xff\xff\xc6\xf0\x70'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
