# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/maximize-2, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x0f\x0f\x0f\x0f\xf0\xf0\xf0\xf0'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
