# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/message-circle, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x3c\x7e\x43\xc3\xc3\x47\xfe\xd8'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
