# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/messages-square, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\xfc\x84\x87\xff\xfd\xe1\x3f\x03'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
