# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/minimize, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x24\x24\xe7\x00\x00\xe7\x24\x24'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
