# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/minimize-2, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x03\x0f\x0e\x0e\x70\x70\xf0\xc0'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
