# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/notebook-text, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x7e\xe2\xfe\xfe\xfe\xfa\xe2\x7e'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
