# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/palette, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x3c\x7e\xfb\xe7\xe3\xce\x78\x38'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
