# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/play, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x60\x78\x5e\x47\x47\x5e\x78\x60'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
