# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/refresh-ccw, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\xfc\xfe\xe3\xc3\xc3\xc7\x7f\x3f'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
