# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/search, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x38\x7c\xc6\xc2\xc6\x6e\x3f\x03'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
