# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/send, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x07\x3f\xff\xfe\x3e\x1e\x0c\x0c'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
