# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/share, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x18\x3c\x3c\x5a\x5a\x5a\x42\x7e'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
