# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/sheet, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x7e\xff\xff\xff\xff\xff\xff\x7e'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
