# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/sparkles, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x1a\x1f\x1a\xff\xff\xd8\xd8\x18'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
