# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/square-pen, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x77\xff\xdf\xfe\xff\xfb\xff\xfe'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
