# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/telescope, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x06\x0f\x7f\xff\xfe\x1c\x3c\x24'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
