# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/text-search, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x00\xff\x7f\xfe\x7e\xff\x77\x00'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
