# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/thumbs-down, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x7f\x45\xc5\xc5\xff\x3c\x38\x18'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
