# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/trending, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x00\x00\x07\x37\x7d\xc8\x00\x00'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
