# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/users, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x34\x7e\x7e\x7e\x7a\xff\x85\x85'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
