# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/waypoints, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x18\x3c\x7a\xff\xff\x5e\x3c\x18'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
