# Auto-generated by icons/build_icons.py — do not edit by hand.
# Source: icons/src/wrench, Size=8px.png
# Size: 8x8

_W = 8
_H = 8
_DATA = b'\x1e\x1f\x1f\x37\x7f\xf8\xf0\xe0'


def width():
    return _W


def height():
    return _H


def data():
    return _DATA
