from drawing.rect import fill_rounded_rect, rounded_rect

from tokens.semantic import (
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_001,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_002,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_003,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_004,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_005,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_006,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_007,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_008,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_009,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_001,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_002,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_003,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_004,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_005,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_006,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_007,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_008,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_009,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_001,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_002,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_003,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_004,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_005,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_006,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_007,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_008,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_009,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_ATTENTION,
)
from tokens.viewport import RADIUS_XS, PADDING_2

_PAD   = PADDING_2   # 4px internal padding each side
_MIN_W = 20          # minimum badge width

_ACCENT_BG = {
    'default': {
        '001': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_009,
    },
    'subtle': {
        '001': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_009,
    },
    'ghost': {
        '001': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_009,
    },
}

_ACCENT_FG = {
    'default': {
        '001': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_009,
    },
    'subtle': {
        '001': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_009,
    },
    'ghost': {
        '001': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_009,
    },
}

_ACCENT_BORDER = {
    'default': {
        '001': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_001,
        '002': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_002,
        '003': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_003,
        '004': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_004,
        '005': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_005,
        '006': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_006,
        '007': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_007,
        '008': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_008,
        '009': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_009,
    },
    'subtle': {
        '001': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_001,
        '002': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_002,
        '003': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_003,
        '004': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_004,
        '005': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_005,
        '006': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_006,
        '007': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_007,
        '008': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_008,
        '009': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_009,
    },
    'ghost': {
        '001': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_001,
        '002': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_002,
        '003': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_003,
        '004': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_004,
        '005': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_005,
        '006': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_006,
        '007': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_007,
        '008': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_008,
        '009': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_009,
    },
}

_SEMANTIC_BG = {
    'default': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_ATTENTION,
    },
    'subtle': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_ATTENTION,
    },
    'ghost': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_ATTENTION,
    },
}

_SEMANTIC_FG = {
    'default': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_ATTENTION,
    },
    'subtle': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_ATTENTION,
    },
    'ghost': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_ATTENTION,
    },
}

_SEMANTIC_BORDER = {
    'default': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_ATTENTION,
    },
    'subtle': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_ATTENTION,
    },
    'ghost': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_ATTENTION,
    },
}

_SEMANTIC_CATS = ('neutral', 'success', 'warning', 'error', 'information', 'attention')


def _is_transparent(c):
    return len(c) == 4 and c[3] == 0


def badge(display, font, text, x, y, category='neutral', emphasis='ghost'):
    """
    Draw a text badge and return its width.

    category: accent number '001'..'009'  OR semantic 'neutral'/'success'/'warning'/'error'/'information'/'attention'
    emphasis: 'default' | 'subtle' | 'ghost'
    Returns the badge width (px) so callers can advance x.
    """
    if category in _SEMANTIC_CATS:
        bg     = _SEMANTIC_BG[emphasis][category]
        fg     = _SEMANTIC_FG[emphasis][category]
        border = _SEMANTIC_BORDER[emphasis][category]
    else:
        bg     = _ACCENT_BG[emphasis][category]
        fg     = _ACCENT_FG[emphasis][category]
        border = _ACCENT_BORDER[emphasis][category]

    tw = font.max_width() * len(text)
    w  = max(_MIN_W, tw + _PAD * 2)
    h  = font.height() + _PAD * 2

    if not _is_transparent(bg):
        fill_rounded_rect(display, x, y, w, h, RADIUS_XS, bg)

    tx = x + (w - tw) // 2
    ty = y + _PAD
    display.write(font, text, tx, ty, fg, None if _is_transparent(bg) else bg)

    if not _is_transparent(border):
        rounded_rect(display, x, y, w, h, RADIUS_XS, border)

    return w
