from drawing.rect import fill_rounded_rect, rounded_rect
from drawing.text import text_w as _text_w
from drawing.icon import draw_icon as _draw_icon

from tokens.semantic import (
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_001,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_002,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_003,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_004,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_005,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_006,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_007,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_008,
    COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_009,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_001,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_002,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_003,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_004,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_005,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_006,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_007,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_008,
    COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_009,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_001,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_002,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_003,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_004,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_005,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_006,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_007,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_008,
    COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_009,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_001,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_002,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_003,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_004,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_005,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_006,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_007,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_008,
    COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_009,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_ATTENTION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_NEUTRAL,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_SUCCESS,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_WARNING,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_ERROR,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_INFORMATION,
    COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_ATTENTION,
)
from tokens.viewport import PADDING_1, PADDING_2, GAP_1, RADIUS_SM
from components.status_dot import status_dot as _draw_status_dot, size as status_dot_size


_ACCENT_BG = {
    'default': {
        '001': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BACKGROUND_009,
    },
    'subtle': {
        '001': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BACKGROUND_009,
    },
    'ghost': {
        '001': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_GHOST_BACKGROUND_009,
    },
}

_ACCENT_FG = {
    'default': {
        '001': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_DEFAULT_FOREGROUND_009,
    },
    'subtle': {
        '001': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_SUBTLE_FOREGROUND_009,
    },
    'ghost': {
        '001': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_001,
        '002': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_002,
        '003': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_003,
        '004': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_004,
        '005': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_005,
        '006': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_006,
        '007': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_007,
        '008': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_008,
        '009': COMMUNICATION_MARKERS_ACCENT_GHOST_FOREGROUND_009,
    },
}

_ACCENT_BORDER = {
    'default': {
        '001': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_001,
        '002': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_002,
        '003': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_003,
        '004': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_004,
        '005': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_005,
        '006': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_006,
        '007': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_007,
        '008': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_008,
        '009': COMMUNICATION_MARKERS_ACCENT_DEFAULT_BORDER_009,
    },
    'subtle': {
        '001': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_001,
        '002': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_002,
        '003': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_003,
        '004': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_004,
        '005': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_005,
        '006': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_006,
        '007': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_007,
        '008': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_008,
        '009': COMMUNICATION_MARKERS_ACCENT_SUBTLE_BORDER_009,
    },
    'ghost': {
        '001': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_001,
        '002': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_002,
        '003': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_003,
        '004': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_004,
        '005': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_005,
        '006': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_006,
        '007': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_007,
        '008': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_008,
        '009': COMMUNICATION_MARKERS_ACCENT_GHOST_BORDER_009,
    },
}

_SEMANTIC_BG = {
    'default': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BACKGROUND_ATTENTION,
    },
    'subtle': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BACKGROUND_ATTENTION,
    },
    'ghost': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_GHOST_BACKGROUND_ATTENTION,
    },
}

_SEMANTIC_FG = {
    'default': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_FOREGROUND_ATTENTION,
    },
    'subtle': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_FOREGROUND_ATTENTION,
    },
    'ghost': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_GHOST_FOREGROUND_ATTENTION,
    },
}

_SEMANTIC_BORDER = {
    'default': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_DEFAULT_BORDER_ATTENTION,
    },
    'subtle': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_SUBTLE_BORDER_ATTENTION,
    },
    'ghost': {
        'neutral':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_NEUTRAL,
        'success':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_SUCCESS,
        'warning':     COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_WARNING,
        'error':       COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_ERROR,
        'information': COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_INFORMATION,
        'attention':   COMMUNICATION_MARKERS_SEMANTIC_GHOST_BORDER_ATTENTION,
    },
}

_SEMANTIC_COLOURS = ('neutral', 'success', 'warning', 'error', 'information', 'attention')

_ICON_SIZE = 8  # Figma icon slot — reserved, drawn only when an icon module is supplied.


def _is_transparent(c):
    return len(c) == 4 and c[3] == 0


def badge(display, font, badge_label, x, y,
          colour='001', emphasis='default', type='accent',
          status_dot=True, icon=True):
    """
    Draw a pill-shaped badge and return its width.

    type:         'accent' | 'semantic'
    colour:       accent   -> '001'..'009'
                  semantic -> 'neutral'|'success'|'warning'|'error'|'information'|'attention'
    emphasis:     'default' | 'subtle' | 'ghost'
    status_dot:   True to draw an inline 4px focus-coloured dot before the label.
    icon:         False — skip the icon slot entirely.
                  True — reserve an empty 8x8 slot between the dot and the label.
                  An icon module — reserve the slot AND draw the icon, tinted with the badge fg.

    Returns the badge width (px) so callers can advance x.
    """
    if colour in _SEMANTIC_COLOURS:
        bg     = _SEMANTIC_BG[emphasis][colour]
        fg     = _SEMANTIC_FG[emphasis][colour]
        border = _SEMANTIC_BORDER[emphasis][colour]
    else:
        bg     = _ACCENT_BG[emphasis][colour]
        fg     = _ACCENT_FG[emphasis][colour]
        border = _ACCENT_BORDER[emphasis][colour]

    fh = font.height()
    # Design system rule: every height is even. Round odd font bitmaps (e.g. Silkscreen 9px)
    # up to the next even line-height — matches Figma's Line-height/Body/Nx tokens exactly.
    font_lh = fh + (fh % 2)
    dot_sz = status_dot_size()
    bg_transparent = _is_transparent(bg)

    content_h = max(
        font_lh,
        _ICON_SIZE if icon else 0,
        dot_sz if status_dot else 0,
    )
    h = content_h + PADDING_1 * 2
    # Figma calls for RADIUS_SM (4). Clamp to h // 2 so small badges still render
    # cleanly when the token exceeds the available radius space.
    r = min(RADIUS_SM, h // 2)

    # Width = left pad + [dot + gap] + [icon + gap] + text + right pad.
    w = PADDING_2 * 2 + _text_w(font, badge_label)
    if status_dot:
        w += dot_sz + GAP_1
    if icon:
        w += _ICON_SIZE + GAP_1

    if not bg_transparent:
        fill_rounded_rect(display, x, y, w, h, r, bg)

    cursor = x + PADDING_2

    if status_dot:
        dot_y = y + (h - dot_sz) // 2
        # Auto-derive the dot's family from colour so the badge's `type` arg can't
        # produce a mismatched (type, colour) pair that crashes status_dot.
        dot_type = 'semantic' if colour in _SEMANTIC_COLOURS else 'accent'
        _draw_status_dot(display, cursor, dot_y, colour=colour, emphasis='default', type=dot_type)
        cursor += dot_sz + GAP_1

    if icon:
        if icon is not True:
            # icon is a module — render it, centred in the 8x8 slot, in the badge fg.
            icon_x = cursor + (_ICON_SIZE - icon.width()) // 2
            icon_y = y + (h - icon.height()) // 2
            _draw_icon(display, icon, icon_x, icon_y, fg)
        cursor += _ICON_SIZE + GAP_1

    text_y = y + (h - fh) // 2
    display.write(font, badge_label, cursor, text_y, fg, None if bg_transparent else bg)

    if not _is_transparent(border):
        rounded_rect(display, x, y, w, h, r, border)

    return w
