from tokens.semantic import (
    COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_001,
    COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_002,
    COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_003,
    COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_004,
    COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_005,
    COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_006,
    COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_007,
    COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_008,
    COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_009,
    COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_NEUTRAL,
    COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_SUCCESS,
    COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_WARNING,
    COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_ERROR,
    COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_INFORMATION,
    COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_ATTENTION,
    COMMUNICATION_HIGHLIGHTS_BACKGROUND_BASE,
)

_SIZE = 4  # 4x4 dot — radius/sm at this size collapses to a full circle visually.

_ACCENT_FILL = {
    '001': COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_001,
    '002': COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_002,
    '003': COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_003,
    '004': COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_004,
    '005': COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_005,
    '006': COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_006,
    '007': COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_007,
    '008': COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_008,
    '009': COMMUNICATION_FOCUS_ACCENT_DEFAULT_BACKGROUND_009,
    'focus': COMMUNICATION_HIGHLIGHTS_BACKGROUND_BASE,
}

_SEMANTIC_FILL = {
    'neutral':     COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_NEUTRAL,
    'success':     COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_SUCCESS,
    'warning':     COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_WARNING,
    'error':       COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_ERROR,
    'information': COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_INFORMATION,
    'attention':   COMMUNICATION_FOCUS_SEMANTIC_DEFAULT_BACKGROUND_ATTENTION,
}


def _is_transparent(c):
    return len(c) == 4 and c[3] == 0


def size():
    return _SIZE


def status_dot(display, x, y, colour='neutral', emphasis='default', type='accent'):
    """
    Draw a 4x4 status dot and return its width.

    type:     'accent' | 'semantic'
    colour:   accent  -> '001'..'009' or 'focus'
              semantic -> 'neutral'|'success'|'warning'|'error'|'information'|'attention'
    emphasis: 'default' (only value Figma exposes — kept for prop-name parity).
    Returns the dot size in px so callers can advance x.
    """
    if type == 'accent':
        fg = _ACCENT_FILL[colour]
    else:
        fg = _SEMANTIC_FILL[colour]

    if _is_transparent(fg):
        return _SIZE

    display.fill_rect(x, y, _SIZE, _SIZE, fg)
    return _SIZE
