#!/usr/bin/env python3
"""
tokens/build_tokens.py

Converts Figma token JSON exports to MicroPython token modules.

Source:  tokens/src/01-primitive/   →  tokens/primitive.py
         tokens/src/02-Semantic/    →  tokens/semantic.py
         tokens/src/03-viewports/   →  tokens/viewport.py

Usage:
    python tokens/build_tokens.py                   # default: xs
    python tokens/build_tokens.py --viewport sm     # sm, md, lg, xl

Re-run whenever you export updated tokens from Figma.
Output files are auto-generated — do not edit by hand.
"""

import argparse
import json
import re
from pathlib import Path

SRC = Path(__file__).parent / "src"
OUT = Path(__file__).parent

VIEWPORTS = ("xs", "sm", "md", "lg", "xl")

# Web-only primitive categories — excluded from primitive.py
SKIP_PRIMITIVE = {"Breakpoint", "Grid", "Areas"}

# Viewport token groups to skip — web layout, not useful on a physical display
SKIP_VIEWPORT = {"Grid", "Columns", "Content", "Adapter"}


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def load_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def flatten(data, prefix=""):
    """Recursively flatten nested token dict into {dot.path: token_object}."""
    result = {}
    for key, value in data.items():
        if key.startswith("$"):
            continue
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict) and "$value" in value:
            result[path] = value
        elif isinstance(value, dict):
            result.update(flatten(value, path))
    return result


def to_name(path):
    """Convert a dot-path to UPPER_SNAKE_CASE Python identifier."""
    return re.sub(r"[^A-Za-z0-9]+", "_", path).upper().strip("_")


def parse_hex(hex_str):
    h = hex_str.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    if len(h) == 8:
        return (r, g, b, int(h[6:8], 16))
    return (r, g, b)


def fmt_color(c):
    return f"({', '.join(str(x) for x in c)})"


def fmt_number(v):
    return int(v) if isinstance(v, float) and v == int(v) else v


def resolve(value, primitive_flat):
    """
    Resolve a {reference} to its Python constant name.
    Returns (py_name, resolved_value) or (None, None) if unresolvable.
    Handles chained references recursively.
    """
    if not (isinstance(value, str) and value.startswith("{") and value.endswith("}")):
        return None, None
    ref_path = value[1:-1]
    if ref_path not in primitive_flat:
        return None, None
    token = primitive_flat[ref_path]
    inner = token.get("$value")
    # If the referenced token is itself a reference, resolve it
    if isinstance(inner, str) and inner.startswith("{"):
        inner_name, inner_val = resolve(inner, primitive_flat)
        return inner_name, inner_val
    return to_name(ref_path), inner


# ---------------------------------------------------------------------------
# primitive.py
# ---------------------------------------------------------------------------

def build_primitives():
    raw = {}
    for f in sorted((SRC / "01-primitive").glob("*.json")):
        raw.update(load_json(f))

    all_tokens = flatten(raw)

    groups = {}
    for path, token in sorted(all_tokens.items()):
        cat = path.split(".")[0]
        if cat in SKIP_PRIMITIVE:
            continue
        groups.setdefault(cat, []).append((path, token))

    lines = [
        "# Auto-generated by tokens/build_tokens.py — do not edit by hand.",
        "# Source: tokens/src/01-primitive/",
        "# Re-run after exporting updated tokens from Figma.",
        "#",
        "# Colors:   (r, g, b)       — opaque",
        "#           (r, g, b, a)    — with alpha  (a=0 fully transparent, a=255 opaque)",
        "# Numbers:  int (px)",
        "# Strings:  font family / weight names",
        "",
    ]

    color_count = num_count = 0

    for cat, entries in sorted(groups.items()):
        lines += [f"# {'─' * 56}", f"# {cat}", f"# {'─' * 56}", ""]
        for path, token in entries:
            t = token.get("$type")
            v = token.get("$value")
            name = to_name(path)

            if t == "color" and isinstance(v, str) and v.startswith("#"):
                color = parse_hex(v)
                suffix = "  # fully transparent" if (len(color) == 4 and color[3] == 0) else ""
                lines.append(f"{name} = {fmt_color(color)}  # {v}{suffix}")
                color_count += 1
            elif t == "number" and isinstance(v, (int, float)):
                lines.append(f"{name} = {fmt_number(v)}")
                num_count += 1
            elif t in ("string", "text") and isinstance(v, str):
                lines.append(f'{name} = "{v}"')
        lines.append("")

    (OUT / "primitive.py").write_text("\n".join(lines), encoding="utf-8")
    print(f"  primitive.py   — {color_count} colors, {num_count} numbers")
    return all_tokens


# ---------------------------------------------------------------------------
# semantic.py
# ---------------------------------------------------------------------------

def build_semantics(primitive_flat, theme="light"):
    theme_file = SRC / "02-Semantic" / f"{theme.capitalize()}.json"
    if not theme_file.exists():
        print(f"  semantic.py    — skipped (no {theme_file.name} found)")
        return

    tokens = flatten(load_json(theme_file))
    resolved = []
    unresolved = []

    for path, token in sorted(tokens.items()):
        v = token.get("$value")
        name = to_name(path)

        if isinstance(v, str) and v.startswith("{") and v.endswith("}"):
            ref_name, _ = resolve(v, primitive_flat)
            if ref_name:
                resolved.append((name, ref_name, v))
            else:
                unresolved.append((name, v))
        elif isinstance(v, str) and v.startswith("#"):
            resolved.append((name, fmt_color(parse_hex(v)), v))
        elif isinstance(v, (int, float)):
            resolved.append((name, str(fmt_number(v)), str(v)))

    lines = [
        "# Auto-generated by tokens/build_tokens.py — do not edit by hand.",
        f"# Source: tokens/src/02-Semantic/{theme.capitalize()}.json",
        "# Re-run after exporting updated tokens from Figma.",
        "",
        "from tokens.primitive import *",
        "",
        "# Each token aliases a primitive by role.",
        "# Names match the Figma semantic token names exactly.",
        "",
        "# ── Resolved ──────────────────────────────────────────────",
        "",
    ]

    for name, ref, original in resolved:
        lines.append(f"{name} = {ref}  # {original}")

    if unresolved:
        lines += [
            "",
            "# ── Unresolved (reference not found in primitives) ────────",
            "",
        ]
        for name, original in unresolved:
            lines.append(f"# {name} = ???  # {original}")

    lines.append("")
    (OUT / "semantic.py").write_text("\n".join(lines), encoding="utf-8")
    print(f"  semantic.py    — {len(resolved)} resolved, {len(unresolved)} unresolved")


# ---------------------------------------------------------------------------
# viewport.py
# ---------------------------------------------------------------------------

def viewport_name(path):
    """
    Generate a clean, collision-free Python name for a viewport token.

    Rules per category:
      Font size.Body.1x         → FONT_SIZE_BODY_1X
      Line-height.Body.1x       → LINE_HEIGHT_BODY_1X
      Spacing.Gap.Gap-4         → GAP_4
      Spacing.Padding.Padding-3 → PADDING_3
      Radius.xs                 → RADIUS_XS
      Radius.3xl                → RADIUS_3XL
    """
    parts = path.split(".")
    cat = parts[0]

    if cat == "Font size":
        rest = to_name(".".join(parts[1:]))
        return f"FONT_SIZE_{rest}"

    elif cat == "Line-height":
        rest = to_name(".".join(parts[1:]))
        return f"LINE_HEIGHT_{rest}"

    elif cat == "Spacing" and len(parts) >= 3:
        sub = parts[1].upper()      # GAP or PADDING
        # Strip repeated prefix: "Gap-4" → "4", "Padding-3" → "3"
        val = re.sub(r"^[A-Za-z]+-?", "", parts[2])
        return f"{sub}_{val}" if val else f"{sub}_{to_name(parts[2])}"

    elif cat == "Radius":
        rest = to_name(".".join(parts[1:]))
        return f"RADIUS_{rest}"

    else:
        return to_name(path)


def build_viewport(viewport, primitive_flat):
    vp_file = SRC / "03-viewports" / f"{viewport.upper()}.json"
    if not vp_file.exists():
        print(f"  viewport.py    — skipped (no {viewport.upper()}.json found)")
        return

    tokens = flatten(load_json(vp_file))

    lines = [
        "# Auto-generated by tokens/build_tokens.py — do not edit by hand.",
        f"# Viewport: {viewport.upper()}",
        "# Source: tokens/src/03-viewports/",
        "# Re-run after exporting updated tokens from Figma.",
        "#",
        "# To switch viewport:  python tokens/build_tokens.py --viewport <xs|sm|md|lg|xl>",
        "",
        "from tokens.primitive import *",
        "",
    ]

    groups = {}
    for path, token in sorted(tokens.items()):
        cat = path.split(".")[0]
        if cat in SKIP_VIEWPORT:
            continue
        groups.setdefault(cat, []).append((path, token))

    resolved_count = unresolved_count = 0

    for cat, entries in sorted(groups.items()):
        lines += [f"# {'─' * 56}", f"# {cat}", f"# {'─' * 56}", ""]
        for path, token in entries:
            v = token.get("$value")
            name = viewport_name(path)

            if isinstance(v, str) and v.startswith("{") and v.endswith("}"):
                ref_name, _ = resolve(v, primitive_flat)
                if ref_name:
                    lines.append(f"{name} = {ref_name}  # {v}")
                    resolved_count += 1
                else:
                    lines.append(f"# {name} = ???  # {v}  (unresolved)")
                    unresolved_count += 1
            elif isinstance(v, (int, float)):
                lines.append(f"{name} = {fmt_number(v)}")
                resolved_count += 1
        lines.append("")

    (OUT / "viewport.py").write_text("\n".join(lines), encoding="utf-8")
    print(f"  viewport.py    — {viewport.upper()}  ({resolved_count} tokens, {unresolved_count} unresolved)")


# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Build pico-ui-kit token modules from Figma JSON exports.")
    parser.add_argument(
        "--viewport",
        choices=VIEWPORTS,
        default="xs",
        help="Viewport to use for spacing, type scale, and radii (default: xs)",
    )
    parser.add_argument(
        "--theme",
        choices=("light", "dark"),
        default="light",
        help="Colour theme to use for semantic tokens (default: light)",
    )
    args = parser.parse_args()

    print(f"Building pico-ui-kit tokens (viewport: {args.viewport.upper()}, theme: {args.theme})...")
    primitive_flat = build_primitives()
    build_semantics(primitive_flat, args.theme)
    build_viewport(args.viewport, primitive_flat)
    print("Done.")


if __name__ == "__main__":
    main()
