#!/usr/bin/env python3
"""
tokens/build_tokens.py

Converts token source JSON to MicroPython token modules.

Source:  tokens/src/01-primitive/   →  tokens/primitive.py
         tokens/src/02-Semantic/    →  tokens/semantic_light.py
                                        tokens/semantic_dark.py
         tokens/src/03-viewports/   →  tokens/viewport.py

tokens/semantic.py is a thin shim that delegates to tokens/colormode.py,
which selects light or dark at boot by reading mode.cfg from flash.

Usage:
    python tokens/build_tokens.py                      # default: theme 1, xs
    python tokens/build_tokens.py --theme 2            # switch colour theme
    python tokens/build_tokens.py --viewport sm        # xs, sm, md, lg, xl
    python tokens/build_tokens.py --theme 2 --viewport sm

Terminology:
    theme    — which primitive colour palette (01-primitive/Mode N.json)
    viewport — spacing, type scale, and radii for the target display

Both light and dark semantic files are always generated together.
Light/dark colour mode selection at runtime is handled by tokens/colormode.py — see README.

Re-run whenever token source JSON is updated.
Output files are auto-generated — do not edit by hand.
"""

import argparse
import json
import re
from pathlib import Path

SRC = Path(__file__).parent / "src"
OUT = Path(__file__).parent

VIEWPORTS = ("xs", "sm", "md", "lg", "xl")

# Web-only primitive categories — excluded from primitive.py
SKIP_PRIMITIVE = {"Breakpoint", "Grid", "Areas"}

# Viewport token groups to skip — web layout, not useful on a physical display
SKIP_VIEWPORT = {"Grid", "Columns", "Content", "Adapter"}


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def load_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def flatten(data, prefix=""):
    """Recursively flatten nested token dict into {dot.path: token_object}."""
    result = {}
    for key, value in data.items():
        if key.startswith("$"):
            continue
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict) and "$value" in value:
            result[path] = value
        elif isinstance(value, dict):
            result.update(flatten(value, path))
    return result


def to_name(path):
    """Convert a dot-path to UPPER_SNAKE_CASE Python identifier."""
    return re.sub(r"[^A-Za-z0-9]+", "_", path).upper().strip("_")


def parse_hex(hex_str):
    h = hex_str.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    if len(h) == 8:
        return (r, g, b, int(h[6:8], 16))
    return (r, g, b)


def fmt_color(c):
    return f"({', '.join(str(x) for x in c)})"


def fmt_number(v):
    return int(v) if isinstance(v, float) and v == int(v) else v


def resolve(value, primitive_flat):
    """
    Resolve a {reference} to its Python constant name.
    Returns (py_name, resolved_value) or (None, None) if unresolvable.
    Handles chained references recursively.
    """
    if not (isinstance(value, str) and value.startswith("{") and value.endswith("}")):
        return None, None
    ref_path = value[1:-1]
    if ref_path not in primitive_flat:
        return None, None
    token = primitive_flat[ref_path]
    inner = token.get("$value")
    # If the referenced token is itself a reference, resolve it
    if isinstance(inner, str) and inner.startswith("{"):
        inner_name, inner_val = resolve(inner, primitive_flat)
        return inner_name, inner_val
    return to_name(ref_path), inner


# ---------------------------------------------------------------------------
# primitive.py
# ---------------------------------------------------------------------------

def build_primitives(theme="1"):
    mode_file = SRC / "01-primitive" / f"Mode {theme}.json"
    if not mode_file.exists():
        available = sorted(f.stem.replace("Mode ", "") for f in (SRC / "01-primitive").glob("Mode *.json"))
        raise SystemExit(
            f"Theme '{theme}' not found (looked for {mode_file.name}). "
            f"Available: {', '.join(available) or 'none — add a Mode N.json file'}"
        )

    all_tokens = flatten(load_json(mode_file))

    groups = {}
    for path, token in sorted(all_tokens.items()):
        cat = path.split(".")[0]
        if cat in SKIP_PRIMITIVE:
            continue
        groups.setdefault(cat, []).append((path, token))

    lines = [
        "# Auto-generated by tokens/build_tokens.py — do not edit by hand.",
        f"# Theme: {theme}  (tokens/src/01-primitive/Mode {theme}.json)",
        "# Re-run after updating token source JSON.",
        "#",
        "# Colors:   (r, g, b)       — opaque",
        "#           (r, g, b, a)    — with alpha  (a=0 fully transparent, a=255 opaque)",
        "# Numbers:  int (px)",
        "# Strings:  font family / weight names",
        "",
    ]

    color_count = num_count = 0

    for cat, entries in sorted(groups.items()):
        lines += [f"# {'─' * 56}", f"# {cat}", f"# {'─' * 56}", ""]
        for path, token in entries:
            t = token.get("$type")
            v = token.get("$value")
            name = to_name(path)

            if t == "color" and isinstance(v, str) and v.startswith("#"):
                color = parse_hex(v)
                suffix = "  # fully transparent" if (len(color) == 4 and color[3] == 0) else ""
                lines.append(f"{name} = {fmt_color(color)}  # {v}{suffix}")
                color_count += 1
            elif t == "number" and isinstance(v, (int, float)):
                lines.append(f"{name} = {fmt_number(v)}")
                num_count += 1
            elif t in ("string", "text") and isinstance(v, str):
                lines.append(f'{name} = "{v}"')
        lines.append("")

    (OUT / "primitive.py").write_text("\n".join(lines), encoding="utf-8")
    print(f"  primitive.py   — {color_count} colors, {num_count} numbers")
    return all_tokens


# ---------------------------------------------------------------------------
# semantic.py
# ---------------------------------------------------------------------------

def build_semantics(primitive_flat, colormode="light", theme="1"):
    cm_file = SRC / "02-Semantic" / f"{colormode.capitalize()}.json"
    out_name = f"semantic_{colormode}"
    if not cm_file.exists():
        print(f"  {out_name}.py — skipped (no {cm_file.name} found)")
        return

    tokens = flatten(load_json(cm_file))
    resolved = []
    unresolved = []

    for path, token in sorted(tokens.items()):
        v = token.get("$value")
        name = to_name(path)

        if isinstance(v, str) and v.startswith("{") and v.endswith("}"):
            ref_name, _ = resolve(v, primitive_flat)
            if ref_name:
                resolved.append((name, ref_name, v))
            else:
                unresolved.append((name, v))
        elif isinstance(v, str) and v.startswith("#"):
            resolved.append((name, fmt_color(parse_hex(v)), v))
        elif isinstance(v, (int, float)):
            resolved.append((name, str(fmt_number(v)), str(v)))

    lines = [
        "# Auto-generated by tokens/build_tokens.py — do not edit by hand.",
        f"# Theme: {theme}  Colour mode: {colormode}  (tokens/src/02-Semantic/{colormode.capitalize()}.json)",
        "# Re-run after updating token source JSON.",
        "",
        "from tokens.primitive import *",
        "",
        "# Each token aliases a primitive by role.",
        "",
        "# ── Resolved ──────────────────────────────────────────────",
        "",
    ]

    for name, ref, original in resolved:
        lines.append(f"{name} = {ref}  # {original}")

    if unresolved:
        lines += [
            "",
            "# ── Unresolved (reference not found in primitives) ────────",
            "",
        ]
        for name, original in unresolved:
            lines.append(f"# {name} = ???  # {original}")

    lines.append("")
    (OUT / f"{out_name}.py").write_text("\n".join(lines), encoding="utf-8")
    print(f"  {out_name}.py — {len(resolved)} resolved, {len(unresolved)} unresolved")


# ---------------------------------------------------------------------------
# viewport.py
# ---------------------------------------------------------------------------

def viewport_name(path):
    """
    Generate a clean, collision-free Python name for a viewport token.

    Rules per category:
      Font size.Body.1x         → FONT_SIZE_BODY_1X
      Line-height.Body.1x       → LINE_HEIGHT_BODY_1X
      Spacing.Gap.Gap-4         → GAP_4
      Spacing.Padding.Padding-3 → PADDING_3
      Radius.xs                 → RADIUS_XS
      Radius.3xl                → RADIUS_3XL
    """
    parts = path.split(".")
    cat = parts[0]

    if cat == "Font size":
        rest = to_name(".".join(parts[1:]))
        return f"FONT_SIZE_{rest}"

    elif cat == "Line-height":
        rest = to_name(".".join(parts[1:]))
        return f"LINE_HEIGHT_{rest}"

    elif cat == "Spacing" and len(parts) >= 3:
        sub = parts[1].upper()      # GAP or PADDING
        # Strip repeated prefix: "Gap-4" → "4", "Padding-3" → "3"
        val = re.sub(r"^[A-Za-z]+-?", "", parts[2])
        return f"{sub}_{val}" if val else f"{sub}_{to_name(parts[2])}"

    elif cat == "Radius":
        rest = to_name(".".join(parts[1:]))
        return f"RADIUS_{rest}"

    else:
        return to_name(path)


def build_viewport(viewport, primitive_flat):
    vp_file = SRC / "03-viewports" / f"{viewport.upper()}.json"
    if not vp_file.exists():
        print(f"  viewport.py    — skipped (no {viewport.upper()}.json found)")
        return

    tokens = flatten(load_json(vp_file))

    lines = [
        "# Auto-generated by tokens/build_tokens.py — do not edit by hand.",
        f"# Viewport: {viewport.upper()}",
        "# Source: tokens/src/03-viewports/",
        "# Re-run after updating token source JSON.",
        "#",
        "# To switch viewport:  python tokens/build_tokens.py --viewport <xs|sm|md|lg|xl>",
        "",
        "from tokens.primitive import *",
        "",
    ]

    groups = {}
    for path, token in sorted(tokens.items()):
        cat = path.split(".")[0]
        if cat in SKIP_VIEWPORT:
            continue
        groups.setdefault(cat, []).append((path, token))

    resolved_count = unresolved_count = 0

    for cat, entries in sorted(groups.items()):
        lines += [f"# {'─' * 56}", f"# {cat}", f"# {'─' * 56}", ""]
        for path, token in entries:
            v = token.get("$value")
            name = viewport_name(path)

            if isinstance(v, str) and v.startswith("{") and v.endswith("}"):
                ref_name, _ = resolve(v, primitive_flat)
                if ref_name:
                    lines.append(f"{name} = {ref_name}  # {v}")
                    resolved_count += 1
                else:
                    lines.append(f"# {name} = ???  # {v}  (unresolved)")
                    unresolved_count += 1
            elif isinstance(v, (int, float)):
                lines.append(f"{name} = {fmt_number(v)}")
                resolved_count += 1
        lines.append("")

    (OUT / "viewport.py").write_text("\n".join(lines), encoding="utf-8")
    print(f"  viewport.py    — {viewport.upper()}  ({resolved_count} tokens, {unresolved_count} unresolved)")


# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Build pico-ui-kit token modules from token source JSON.")
    parser.add_argument(
        "--theme",
        default="1",
        metavar="N",
        help="Colour theme to build from — corresponds to '01-primitive/Mode N.json' (default: 1)",
    )
    parser.add_argument(
        "--viewport",
        choices=VIEWPORTS,
        default="xs",
        help="Viewport to use for spacing, type scale, and radii (default: xs)",
    )
    args = parser.parse_args()

    print(f"Building pico-ui-kit tokens (theme: {args.theme}, viewport: {args.viewport.upper()})...")
    primitive_flat = build_primitives(args.theme)
    build_semantics(primitive_flat, "light", args.theme)
    build_semantics(primitive_flat, "dark", args.theme)

    shim_lines = [
        "# Auto-generated by tokens/build_tokens.py — do not edit by hand.",
        "# Delegates to tokens/colormode.py, which selects light or dark at boot.",
        "# To switch colour mode: write 'light' or 'dark' to mode.cfg on the device, then reset.",
        "from tokens.colormode import *",
        "",
    ]
    (OUT / "semantic.py").write_text("\n".join(shim_lines), encoding="utf-8")
    print("  semantic.py    — shim (delegates to tokens/colormode.py)")

    build_viewport(args.viewport, primitive_flat)
    print("Done.")


if __name__ == "__main__":
    main()
