# Auto-generated by tokens/build_tokens.py — do not edit by hand.
# Delegates to tokens/colormode.py, which selects light or dark at boot.
# To switch colour mode: write 'light' or 'dark' to mode.cfg on the device, then reset.
from tokens.colormode import *
