# Auto-generated by tokens/build_tokens.py — do not edit by hand.
# Viewport: XS
# Source: tokens/src/03-viewports/
#
# To switch viewport:  python tokens/build_tokens.py --viewport <xs|sm|md|lg|xl>

from tokens.primitive import *

# ────────────────────────────────────────────────────────
# Font size
# ────────────────────────────────────────────────────────

FONT_SIZE_BODY_1X = TYPOGRAPHY_FONT_SIZE_015  # {Typography.Font size.015}
FONT_SIZE_BODY_2X = TYPOGRAPHY_FONT_SIZE_100  # {Typography.Font size.100}
FONT_SIZE_BODY_3X = TYPOGRAPHY_FONT_SIZE_500  # {Typography.Font size.500}
FONT_SIZE_BODY_4X = TYPOGRAPHY_FONT_SIZE_700  # {Typography.Font size.700}
FONT_SIZE_HEADERS_LARGE = TYPOGRAPHY_FONT_SIZE_600  # {Typography.Font size.600}
FONT_SIZE_HEADERS_MEDIUM = TYPOGRAPHY_FONT_SIZE_300  # {Typography.Font size.300}
FONT_SIZE_HEADERS_SMALL = TYPOGRAPHY_FONT_SIZE_200  # {Typography.Font size.200}
FONT_SIZE_LABEL_1X = TYPOGRAPHY_FONT_SIZE_007  # {Typography.Font size.007}

# ────────────────────────────────────────────────────────
# Line-height
# ────────────────────────────────────────────────────────

LINE_HEIGHT_BODY_1X = TYPOGRAPHY_LINE_HEIGHT_50  # {Typography.Line-height.50}
LINE_HEIGHT_BODY_2X = TYPOGRAPHY_LINE_HEIGHT_100  # {Typography.Line-height.100}
LINE_HEIGHT_BODY_3X = TYPOGRAPHY_LINE_HEIGHT_500  # {Typography.Line-height.500}
LINE_HEIGHT_BODY_4X = TYPOGRAPHY_LINE_HEIGHT_700  # {Typography.Line-height.700}
LINE_HEIGHT_HEADERS_LARGE = TYPOGRAPHY_LINE_HEIGHT_850  # {Typography.Line-height.850}
LINE_HEIGHT_HEADERS_MEDIUM = TYPOGRAPHY_LINE_HEIGHT_575  # {Typography.Line-height.575}
LINE_HEIGHT_HEADERS_SMALL = TYPOGRAPHY_LINE_HEIGHT_500  # {Typography.Line-height.500}
LINE_HEIGHT_LABEL_1X = TYPOGRAPHY_LINE_HEIGHT_25  # {Typography.Line-height.25}

# ────────────────────────────────────────────────────────
# Radius
# ────────────────────────────────────────────────────────

RADIUS_3XL = RADIUS_SYSTEM_800  # {Radius.System.800}
RADIUS_NULL = RADIUS_SYSTEM_000  # {Radius.System.000}
RADIUS_LG = RADIUS_SYSTEM_500  # {Radius.System.500}
RADIUS_MD = RADIUS_SYSTEM_300  # {Radius.System.300}
RADIUS_SM = RADIUS_SYSTEM_200  # {Radius.System.200}
RADIUS_XS = RADIUS_SYSTEM_100  # {Radius.System.100}

# ────────────────────────────────────────────────────────
# Spacing
# ────────────────────────────────────────────────────────

GAP_0 = SIZING_000  # {Sizing.000}
GAP_1 = SIZING_025  # {Sizing.025}
GAP_2 = SIZING_050  # {Sizing.050}
GAP_3 = SIZING_100  # {Sizing.100}
GAP_4 = SIZING_150  # {Sizing.150}
GAP_5 = SIZING_200  # {Sizing.200}
GAP_6 = SIZING_300  # {Sizing.300}
GAP_7 = SIZING_400  # {Sizing.400}
GAP_8 = SIZING_500  # {Sizing.500}
GAP_9 = SIZING_600  # {Sizing.600}
PADDING_0 = SIZING_000  # {Sizing.000}
PADDING_1 = SIZING_025  # {Sizing.025}
PADDING_10 = SIZING_500  # {Sizing.500}
PADDING_11 = SIZING_550  # {Sizing.550}
PADDING_12 = SIZING_600  # {Sizing.600}
PADDING_13 = SIZING_650  # {Sizing.650}
PADDING_14 = SIZING_700  # {Sizing.700}
PADDING_2 = SIZING_050  # {Sizing.050}
PADDING_3 = SIZING_100  # {Sizing.100}
PADDING_4 = SIZING_200  # {Sizing.200}
PADDING_5 = SIZING_250  # {Sizing.250}
PADDING_6 = SIZING_300  # {Sizing.300}
PADDING_7 = SIZING_350  # {Sizing.350}
PADDING_8 = SIZING_400  # {Sizing.400}
PADDING_9 = SIZING_450  # {Sizing.450}
